# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentomatic', '0002_auto_20161121_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='rented',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='rented_until',
        ),
        migrations.AddField(
            model_name='rent',
            name='end_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rent',
            name='start_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
